### ISSUE TITLE
Can't override slider template

### ISSUE THREAD

**Issue by t-n-y** [netgen-layouts/layouts-sylius#8]
Hi,

i am using V1.3.1 of the layouts-sylius and 1.3.0 of the layouts-standard.
I try to override the slider template because i need to get the images from aws and not on my server.
Did a classic override with a `NetgenLayoutsStandardBundle` directory in the templates directory. And overrided `nglayouts/themes/standard/block/gallery/slider.html.twig`.

But unfortunatly, nothing happen and i can't find a way to make a custom template. Is it a way i can do that ?

Thank you for you help

**Comment by emodric** [comment]
Hi @t-n-y 

Can you provide the exact path of your overrided template?

Since Netgen Layouts has its own theming engine, overriding the template is quite simple, you just need to place it in `templates/nglayouts/themes/standard/block/gallery/slider.html.twig`, without any references to `NetgenLayoutsStandardBundle`.

**Comment by emodric** [comment]
More info here: https://docs.netgen.io/projects/layouts/en/latest/cookbook/using_themes.html#overriding-the-templates-for-existing-layouts-or-blocks

**Comment by t-n-y** [comment]
hi @emodric ,

Thanks a lot ! i didn't found that documentation page. Tried with that path and it works well

**Comment by emodric** [comment]
Glad to hear it!
